#!/usr/bin/env python3

from array import *
import os
import sys
import termios
import fcntl

storage = array('B',[0] * 30000)
dp = 0

def putchars(charval, count):
    for i in range(count):
       print(chr(charval),end='')
       
print("Begin Python3 execution")

