' Gambas module file

Patterns As Collection = ["C1": ["(\n[ ]*)while\\(\\*dp>0\\)\\{\n[ ]*\\(\\*dp\\)--;\n[ ]*\\}", "&1*dp=0;"],
    "C2": ["(\n[ ]*)\\*dp \\+=.*;\n[ ]*\\*dp=0;", "&1*dp=0;"],
    "C3": ["(\n[ ]*)\\*dp -=.*;\n[ ]*\\*dp=0;", "&1*dp=0;"]
]

Public Sub _call(source As String) As String

    TextInfo.BFOutput.Print("Optimizing " & JitCompiler.CodeNames[JitCompiler.X86_asm_code] & "\n\r")
    Dim newSource As String = source
    Dim changed As Boolean = True
    While changed
        changed = False
        For Each Replacement As String[] In Patterns
            Dim oldSource As String = newSource
            newSource = RegExp.Replace(newSource, Replacement[0], Replacement[1])
            If oldSource <> newSource Then changed = True
        Next

    Wend

    Return newSource

End
