' Gambas module file

' cmp byte[rdi], 0
'     jz lab3
' lab1:
'         Dec byte[rdi]
'     cmp byte[rdi], 0
'     jnz lab1
' lab3:
Patterns As Collection = ["C1": ["\n[ ]* cmp byte[rdi], 0\n[ ]*jz lab.*\nlab.*:\n[ ]*Dec byte[rdi]\n[ ]*cmp byte[rdi], 0\n[ ]* jnz lab.*\nlab.*:\n", "mov byte[rdi],0\n"]
]

Public Sub _call(source As String) As String
      
      TextInfo.BFOutput.Print("Optimizing " & JitCompiler.CodeNames[JitCompiler.C_code] & "\n\r")
      Dim newSource As String = source
      Dim changed As Boolean = True
      While changed
            changed = False
            For Each Replacement As String[] In Patterns
                  Dim oldSource As String = newSource
                  newSource = RegExp.Replace(newSource, Replacement[0], Replacement[1])
                  If oldSource <> newSource Then changed = True
            Next
            
      Wend 
      
      Return newSource
      
End
